Repository aerostack2/aerostack2, pull requests merged in 2022-12, with the labels that each got.

#10 As2 Realsense Interface
  as2_hardware_drivers/as2_realsense_interface/.clang-format
  as2_hardware_drivers/as2_realsense_interface/.gitignore
  as2_hardware_drivers/as2_realsense_interface/CMakeLists.txt
  as2_hardware_drivers/as2_realsense_interface/README.md
  as2_hardware_drivers/as2_realsense_interface/config/realsense_interface/d435i/params.yaml
  as2_hardware_drivers/as2_realsense_interface/config/realsense_interface/d435i/tf_sensors.yaml
  as2_hardware_drivers/as2_realsense_interface/config/realsense_interface/t265/params.yaml
  as2_hardware_drivers/as2_realsense_interface/config/realsense_interface/t265/tf_sensors.yaml
  as2_hardware_drivers/as2_realsense_interface/config/tf_device/d435i.yaml
  as2_hardware_drivers/as2_realsense_interface/config/tf_device/t265.yaml
  as2_hardware_drivers/as2_realsense_interface/doxygen.dox
  as2_hardware_drivers/as2_realsense_interface/include/as2_realsense_interface/as2_realsense_interface.hpp
  as2_hardware_drivers/as2_realsense_interface/launch/as2_realsense_interface_launch.py
  as2_hardware_drivers/as2_realsense_interface/launch/as2_realsense_interface_t265_launch.py
  as2_hardware_drivers/as2_realsense_interface/package.xml
  as2_hardware_drivers/as2_realsense_interface/src/as2_realsense_interface.cpp
  as2_hardware_drivers/as2_realsense_interface/src/as2_realsense_interface_node.cpp
  as2_hardware_drivers/realsense_interface/.clang-format
  as2_hardware_drivers/realsense_interface/.gitignore
  as2_hardware_drivers/realsense_interface/CMakeLists.txt
  as2_hardware_drivers/realsense_interface/README.md
  as2_hardware_drivers/realsense_interface/config/realsense_interface/d435i/params.yaml
  as2_hardware_drivers/realsense_interface/config/realsense_interface/d435i/tf_sensors.yaml
  as2_hardware_drivers/realsense_interface/config/realsense_interface/t265/params.yaml
  as2_hardware_drivers/realsense_interface/config/realsense_interface/t265/tf_sensors.yaml
  as2_hardware_drivers/realsense_interface/config/tf_device/d435i.yaml
  as2_hardware_drivers/realsense_interface/config/tf_device/t265.yaml
  as2_hardware_drivers/realsense_interface/doxygen.dox
  as2_hardware_drivers/realsense_interface/include/realsense_interface/realsense_interface.hpp
  as2_hardware_drivers/realsense_interface/launch/realsense_interface_launch.py
  as2_hardware_drivers/realsense_interface/launch/realsense_interface_t265_launch.py
  as2_hardware_drivers/realsense_interface/package.xml
  as2_hardware_drivers/realsense_interface/src/realsense_interface.cpp
  as2_hardware_drivers/realsense_interface/src/realsense_interface_node.cpp
Labels: enhancement

#24 Added Aruco_detector
  as2_behaviors/aruco_detector/.clang-format
  as2_behaviors/aruco_detector/.gitignore
  as2_behaviors/aruco_detector/CMakeLists.txt
  as2_behaviors/aruco_detector/Camera_calibration.txt
  as2_behaviors/aruco_detector/README.md
  as2_behaviors/aruco_detector/action/ArucoDetector.action
  as2_behaviors/aruco_detector/config/as2_aruco_detector/real_params.yaml
  as2_behaviors/aruco_detector/config/as2_aruco_detector/sim_params.yaml
  as2_behaviors/aruco_detector/config/as2_aruco_detector/sim_params_old.yaml
  as2_behaviors/aruco_detector/config/iris_cam/camera_info.yaml
  as2_behaviors/aruco_detector/config/tf_cam/real_arguments.yaml
  as2_behaviors/aruco_detector/config/tf_cam/sim_arguments.yaml
  as2_behaviors/aruco_detector/doxygen.dox
  as2_behaviors/aruco_detector/include/as2_aruco_detector/as2_aruco_detector.hpp
  as2_behaviors/aruco_detector/launch/as2_aruco_detector_real_launch.py
  as2_behaviors/aruco_detector/launch/as2_aruco_detector_sim_launch.py
  as2_behaviors/aruco_detector/launch/test.launch.py
  as2_behaviors/aruco_detector/package.xml
  as2_behaviors/aruco_detector/src/as2_aruco_detector.cpp
  as2_behaviors/aruco_detector/src/as2_aruco_detector_node.cpp
  as2_behaviors/aruco_detector/tests/CMakeLists.txt
  as2_behaviors/aruco_detector/tests/aruco_detection.cpp
  as2_behaviors/aruco_detector/tests/aruco_img.png
  as2_behaviors/aruco_detector/usb_cam/config/camera_info.yaml
  as2_behaviors/aruco_detector/usb_cam/config/params.yaml
Labels: enhancement

#27 Added Usb_camera_interface
  as2_hardware_drivers/as2_hardware_drivers/package.xml
  as2_hardware_drivers/as2_usb_camera_interface/.clang-format
  as2_hardware_drivers/as2_usb_camera_interface/.gitignore
  as2_hardware_drivers/as2_usb_camera_interface/CMakeLists.txt
  as2_hardware_drivers/as2_usb_camera_interface/Camera_calibration.txt
  as2_hardware_drivers/as2_usb_camera_interface/config/as2_usb_camera_interface/camera_info.yaml
  as2_hardware_drivers/as2_usb_camera_interface/config/as2_usb_camera_interface/params.yaml
  as2_hardware_drivers/as2_usb_camera_interface/config/as2_usb_camera_interface/wide03_1080_info.yaml
  as2_hardware_drivers/as2_usb_camera_interface/config/as2_usb_camera_interface/wide03_720_info.yaml
  as2_hardware_drivers/as2_usb_camera_interface/config/tf_cam/f330_arguments.yaml
  as2_hardware_drivers/as2_usb_camera_interface/config/tf_cam/f450_arguments.yaml
  as2_hardware_drivers/as2_usb_camera_interface/config/tf_cam/sim_arguments.yaml
  as2_hardware_drivers/as2_usb_camera_interface/include/as2_usb_camera_interface/as2_usb_camera_interface.hpp
  as2_hardware_drivers/as2_usb_camera_interface/launch/as2_usb_camera_interface_launch.py
  as2_hardware_drivers/as2_usb_camera_interface/package.xml
  as2_hardware_drivers/as2_usb_camera_interface/src/as2_usb_camera_interface.cpp
  as2_hardware_drivers/as2_usb_camera_interface/src/as2_usb_camera_interface_node.cpp
Labels: enhancement

#30 test added to ci
  .github/workflows/build-galactic.yaml
  .github/workflows/build-humble.yaml
  .github/workflows/codeql.yml
  as2_controller/as2_controller_plugin_differential_flatness/package.xml
  as2_controller/as2_controller_plugin_differential_flatness/tests/tests_cmake.cmake
  as2_core/CMakeLists.txt
  as2_core/package.xml
  as2_core/tests/CMakeLists.txt
Labels: CI

#29 Solve as2_aruco_detector action bug
  as2_behaviors/aruco_detector/CMakeLists.txt
  as2_behaviors/aruco_detector/package.xml
  as2_behaviors/aruco_detector/usb_cam/config/camera_info.yaml
  as2_behaviors/aruco_detector/usb_cam/config/params.yaml
  as2_behaviors/as2_behaviors/package.xml
  as2_msgs/CMakeLists.txt
  as2_msgs/action/ArucoDetector.action
Labels: enhancement

#40 Solve as2_realsense_interface dependecy problem
  as2_hardware_drivers/as2_realsense_interface/include/as2_realsense_interface/as2_realsense_interface.hpp
  as2_hardware_drivers/as2_realsense_interface/package.xml
  as2_hardware_drivers/as2_realsense_interface/src/as2_realsense_interface.cpp
Labels: enhancement

#35 try to add code coverage
  .github/workflows/build-galactic.yaml
  .github/workflows/build-humble.yaml
  codecov.yaml
  codecov.yml
Labels: CI

#84 [CI] Clang format fixed
  as2_aerial_platforms/as2_crazyflie_platform/src/crazyflie_platform.cpp
  as2_controller/as2_controller_plugin_differential_flatness/tests/plugin_test.cpp
Labels: CI

#97 Dependency removed
  as2_hardware_drivers/as2_usb_camera_interface/include/as2_usb_camera_interface/as2_usb_camera_interface.hpp
Labels: bug

#101 Added opencv lib
  as2_behaviors/as2_aruco_detector/CMakeLists.txt
Labels: bug
