Repository aerostack2/aerostack2, pull requests merged in 2023-09, with the labels that each got.

#331 [as2_python_api] Improve MissionUpdate message
  as2_msgs/msg/MissionUpdate.msg
  as2_python_api/as2_python_api/mission_interpreter/dummy_mission.json
  as2_python_api/as2_python_api/mission_interpreter/mission.py
  as2_python_api/as2_python_api/mission_interpreter/mission_interpreter.py
  as2_python_api/as2_python_api/mission_interpreter/mission_stack.py
  as2_python_api/as2_python_api/mission_interpreter/my_mission.json
  as2_python_api/as2_python_api/mission_interpreter/ros2_adapter.py
  as2_python_api/as2_python_api/mission_interpreter/test_interpreter.py
  as2_python_api/as2_python_api/modules/module_base.py
  as2_python_api/as2_python_api/tools/utils.py
Labels: python_api

#327 Deal with low latency frames
  as2_behaviors/as2_behaviors_motion/follow_path_behavior/config/config_default.yaml
  as2_behaviors/as2_behaviors_motion/follow_path_behavior/include/follow_path_behavior/follow_path_base.hpp
  as2_behaviors/as2_behaviors_motion/follow_path_behavior/include/follow_path_behavior/follow_path_behavior.hpp
  as2_behaviors/as2_behaviors_motion/follow_reference_behavior/include/follow_reference_behavior/follow_reference_behavior.hpp
  as2_behaviors/as2_behaviors_motion/land_behavior/config/config_default.yaml
  as2_behaviors/as2_behaviors_motion/land_behavior/include/land_behavior/land_base.hpp
  as2_behaviors/as2_behaviors_motion/land_behavior/include/land_behavior/land_behavior.hpp
  as2_behaviors/as2_behaviors_motion/takeoff_behavior/config/config_default.yaml
  as2_behaviors/as2_behaviors_motion/takeoff_behavior/include/takeoff_behavior/takeoff_base.hpp
  as2_behaviors/as2_behaviors_motion/takeoff_behavior/include/takeoff_behavior/takeoff_behavior.hpp
  as2_core/include/as2_core/utils/tf_utils.hpp
  as2_core/src/utils/tf_utils.cpp
  as2_motion_controller/config/motion_controller_default.yaml
  as2_motion_controller/include/as2_motion_controller/controller_handler.hpp
  as2_motion_controller/src/controller_handler.cpp
Labels: bug, enhancement

#337 Add camera change source topic
  as2_aerial_platforms/as2_platform_dji_osdk/include/dji_camera_handler.hpp
Labels: enhancement
