Repository aerostack2/aerostack2, pull requests merged in 2023-03, with the labels that each got.

#189 Clean launcher parameters
  as2_aerial_platforms/as2_platform_crazyflie/launch/crazyflie_swarm_launch.py
  as2_aerial_platforms/as2_platform_crazyflie/scripts/aideck_node.py
Labels: enhancement

#199 [as2_behaviors_motion] Follow Reference Behavior Transforms Error
  as2_behaviors/as2_behaviors_motion/follow_reference_behavior/include/follow_reference_behavior/follow_reference_behavior.hpp
  as2_behaviors/as2_behaviors_motion/launch/motion_behaviors_launch.py
Labels: bug, behavior

#201 [as2_keyboard_teleoperation] remove everything related to attitude mode
  as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/config_values.py
  as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/keyboard_teleoperation.py
  as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/main_window.py
  as2_user_interfaces/as2_keyboard_teleoperation/as2_keyboard_teleoperation/settings_window.py
Labels: bug
