Repository aerostack2/aerostack2, pull requests merged in 2023-11, with the labels that each got.

#355 Geofence messages removed from as2_msgs
  as2_msgs/CMakeLists.txt
  as2_msgs/msg/Geofence.msg
  as2_msgs/srv/GetGeofence.srv
  as2_msgs/srv/SetGeofence.srv
Labels: bug

#356 [as2_motion_controller] Add trajectory reference to actuators commands
  as2_core/include/as2_core/aerial_platform.hpp
  as2_core/include/as2_core/names/topics.hpp
  as2_core/src/aerial_platform.cpp
  as2_motion_controller/include/as2_motion_controller/controller_handler.hpp
  as2_motion_controller/src/controller_handler.cpp
Labels: enhancement

#357 [as2_motion_controller] Refractor CMakeLists.txt for creating a dynamic lib for each plugin
  as2_motion_controller/CMakeLists.txt
  as2_motion_controller/include/as2_motion_controller/controller_base.hpp
  as2_motion_controller/launch/controller_launch.py
  as2_motion_controller/package.xml
  as2_motion_controller/plugins.xml
  as2_motion_controller/plugins/differential_flatness_controller/CMakeLists.txt
  as2_motion_controller/plugins/differential_flatness_controller/tests/controller_node.cpp
  as2_motion_controller/plugins/differential_flatness_controller/tests/plugin_test.cpp
  as2_motion_controller/plugins/differential_flatness_controller/tests/profiling_cmake.cmake
  as2_motion_controller/plugins/differential_flatness_controller/tests/test_performance_controller_benchmark.cpp
  as2_motion_controller/plugins/differential_flatness_controller/tests/tests_cmake.cmake
  as2_motion_controller/plugins/pid_speed_controller/CMakeLists.txt
  as2_motion_controller/tests/unit_test.cmake
Labels: enhancement

#362 [as2_core] Add node options to aerial platform
  as2_core/include/as2_core/aerial_platform.hpp
  as2_core/src/aerial_platform.cpp
Labels: enhancement

#358 [as2_behaviors] Behaviors composable nodes
  as2_behaviors/as2_behavior/include/as2_behavior/__detail/behavior_server__class.hpp
  as2_behaviors/as2_behavior/include/as2_behavior/__impl/behavior_server__impl.hpp
  as2_behaviors/as2_behaviors_motion/CMakeLists.txt
  as2_behaviors/as2_behaviors_motion/follow_path_behavior/include/follow_path_behavior/follow_path_behavior.hpp
  as2_behaviors/as2_behaviors_motion/follow_path_behavior/src/follow_path_behavior.cpp
  as2_behaviors/as2_behaviors_motion/follow_reference_behavior/include/follow_reference_behavior/follow_reference_behavior.hpp
  as2_behaviors/as2_behaviors_motion/follow_reference_behavior/src/follow_reference_behavior.cpp
  as2_behaviors/as2_behaviors_motion/go_to_behavior/include/go_to_behavior/go_to_behavior.hpp
  as2_behaviors/as2_behaviors_motion/go_to_behavior/src/go_to_behavior.cpp
  as2_behaviors/as2_behaviors_motion/land_behavior/include/land_behavior/land_behavior.hpp
  as2_behaviors/as2_behaviors_motion/land_behavior/src/land_behavior.cpp
  as2_behaviors/as2_behaviors_motion/launch/composable_follow_reference.launch.py
  as2_behaviors/as2_behaviors_motion/launch/composable_motion_behaviors.launch.py
  as2_behaviors/as2_behaviors_motion/package.xml
  as2_behaviors/as2_behaviors_motion/takeoff_behavior/include/takeoff_behavior/takeoff_behavior.hpp
  as2_behaviors/as2_behaviors_motion/takeoff_behavior/src/takeoff_behavior.cpp
  as2_behaviors/as2_behaviors_trajectory_generation/CMakeLists.txt
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/CMakeLists.txt
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/launch/composable_generate_polynomial_trajectory_behavior.launch.py
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
  as2_behaviors/as2_behaviors_trajectory_generation/package.xml
Labels: behavior

#367 [as2_motion_controller] Update PID controller dependence to v1.0
  as2_motion_controller/plugins/pid_speed_controller/CMakeLists.txt
  as2_motion_controller/plugins/pid_speed_controller/include/pid_speed_controller/pid_speed_controller.hpp
  as2_motion_controller/plugins/pid_speed_controller/src/pid_speed_controller.cpp
Labels: enhancement
