Repository aerostack2/aerostack2, pull requests merged in 2023-05, with the labels that each got.

#237 Unify launchers
  as2_aerial_platforms/as2_platform_crazyflie/config/aideck_config_file.yaml
  as2_aerial_platforms/as2_platform_crazyflie/config/control_modes.yaml
  as2_aerial_platforms/as2_platform_crazyflie/config/crazy_swarm.yaml
  as2_aerial_platforms/as2_platform_crazyflie/config/platform_config_file.yaml
  as2_aerial_platforms/as2_platform_crazyflie/config/swarm_config_file.yaml
  as2_aerial_platforms/as2_platform_crazyflie/launch/aideck_stream_launch.py
  as2_aerial_platforms/as2_platform_crazyflie/launch/crazyflie_aideck_stream_launch.py
  as2_aerial_platforms/as2_platform_crazyflie/launch/crazyflie_platform_launch.py
  as2_aerial_platforms/as2_platform_crazyflie/launch/crazyflie_platform_with_aideck_launch.py
  as2_aerial_platforms/as2_platform_crazyflie/launch/crazyflie_swarm_launch.py
  as2_aerial_platforms/as2_platform_crazyflie/src/crazyflie_swarm_nodes.cpp
  as2_aerial_platforms/as2_platform_dji_osdk/config/platform_config_file.yaml
  as2_aerial_platforms/as2_platform_dji_osdk/config/platform_default.yaml
  as2_aerial_platforms/as2_platform_dji_osdk/config/user_config_file.txt
  as2_aerial_platforms/as2_platform_dji_osdk/launch/as2_platform_dji_osdk_launch.py
  as2_aerial_platforms/as2_platform_ign_gazebo/config/platform_config_file.yaml
  as2_aerial_platforms/as2_platform_ign_gazebo/launch/ign_gazebo_launch.py
  as2_aerial_platforms/as2_platform_tello/config/platform_config_file.yaml
  as2_aerial_platforms/as2_platform_tello/launch/tello_platform.launch.py
  as2_behaviors/as2_behaviors_motion/CMakeLists.txt
  as2_behaviors/as2_behaviors_motion/follow_path_behavior/config/config_default.yaml
  as2_behaviors/as2_behaviors_motion/follow_reference_behavior/config/config_default.yaml
  as2_behaviors/as2_behaviors_motion/go_to_behavior/config/config_default.yaml
  as2_behaviors/as2_behaviors_motion/land_behavior/config/config_default.yaml
  as2_behaviors/as2_behaviors_motion/launch/follow_path_behavior_launch.py
  as2_behaviors/as2_behaviors_motion/launch/follow_reference_behavior_launch.py
  as2_behaviors/as2_behaviors_motion/launch/go_to_behavior_launch.py
  as2_behaviors/as2_behaviors_motion/launch/land_behavior_launch.py
  as2_behaviors/as2_behaviors_motion/launch/motion_behaviors_launch.py
  as2_behaviors/as2_behaviors_motion/launch/takeoff_behavior_launch.py
  as2_behaviors/as2_behaviors_motion/takeoff_behavior/config/config_default.yaml
  as2_motion_controller/config/motion_controller_default.yaml
  as2_motion_controller/launch/controller_launch.py
  as2_motion_controller/plugins/differential_flatness_controller/config/controller_default.yaml
  as2_motion_controller/plugins/differential_flatness_controller/config/default_controller.yaml
  as2_motion_controller/plugins/pid_speed_controller/config/controller_default.yaml
  as2_motion_controller/src/controller_manager.cpp
  as2_simulation_assets/as2_ign_gazebo_assets/launch/drone_bridges.py
  as2_simulation_assets/as2_ign_gazebo_assets/launch/launch_simulation.py
  as2_simulation_assets/as2_ign_gazebo_assets/launch/monitor_sim.py
  as2_simulation_assets/as2_ign_gazebo_assets/launch/object_bridges.py
  installers/projects.repos
Labels: enhancement

#258 [as2_python_api] Mission updates: reset, append and insert
  as2_msgs/CMakeLists.txt
  as2_msgs/msg/MissionUpdate.msg
  as2_python_api/as2_python_api/mission_interpreter/mission_interpreter.py
Labels: python_api

#260 [as2_motion_reference_handlers] Change JointTrajectoryPoint to TrajectoryPoint msg type
  as2_motion_reference_handlers/as2_motion_reference_handlers/basic_motion_references.py
Labels: bug, behavior

#262 Add badges to readme
  README.md
Labels: documentation

#267 added frame_id argument to go_to
  as2_python_api/as2_python_api/modules/go_to_module.py
Labels: enhancement
