Repository aerostack2/aerostack2, pull requests merged in 2024-04, with the labels that each got.

#448 [as2_motion_controller_manager] Publish speed limits when bypassing and control mode is Position
  as2_motion_controller/src/controller_handler.cpp
Labels: enhancement

#449 [as2_core] Add GroundTruth to handler ground truth publish
  as2_core/include/as2_core/sensor.hpp
  as2_core/src/sensor.cpp
  as2_core/tests/sensor_test.cpp
Labels: enhancement

#450 [as2_gazebo_assets] Sensor model name and sensor link name were swapped in camera bridges
  as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/payload.py
Labels: bug

#452 [as2_core] Add launch params utils
  as2_core/as2_core/launch_param_utils.py
Labels: enhancement

#293 [as2_behaviors_motion] Fix warning about service client access
  as2_behaviors/as2_behaviors_motion/land_behavior/plugins/land_plugin_platform.cpp
  as2_behaviors/as2_behaviors_motion/takeoff_behavior/plugins/takeoff_plugin_platform.cpp
Labels: enhancement, behavior

#461 [as2_core] Refactor sensors and add gimbal sensor
  as2_core/include/as2_core/sensor.hpp
  as2_core/src/sensor.cpp
  as2_core/tests/sensor_test.cpp
Labels: enhancement

#463 [as2_multirotor_simulator] Add as2_multirotor_simulator package
  aerostack2/package.xml
  as2_aerial_platforms/as2_platform_multirotor_simulator/.gitignore
  as2_aerial_platforms/as2_platform_multirotor_simulator/CMakeLists.txt
  as2_aerial_platforms/as2_platform_multirotor_simulator/CONTRIBUTING.md
  as2_aerial_platforms/as2_platform_multirotor_simulator/Doxyfile
  as2_aerial_platforms/as2_platform_multirotor_simulator/LICENSE
  as2_aerial_platforms/as2_platform_multirotor_simulator/README.md
  as2_aerial_platforms/as2_platform_multirotor_simulator/config/control_modes.yaml
  as2_aerial_platforms/as2_platform_multirotor_simulator/config/platform_config_file.yaml
  as2_aerial_platforms/as2_platform_multirotor_simulator/config/simulation_config.yaml
  as2_aerial_platforms/as2_platform_multirotor_simulator/config/uav_config.yaml
  as2_aerial_platforms/as2_platform_multirotor_simulator/config/world_config.yaml
  as2_aerial_platforms/as2_platform_multirotor_simulator/include/as2_platform_multirotor_simulator/as2_platform_multirotor_simulator.hpp
  as2_aerial_platforms/as2_platform_multirotor_simulator/launch/as2_platform_multirotor_simulator.launch.py
  as2_aerial_platforms/as2_platform_multirotor_simulator/launch/as2_platform_multirotor_simulator_world.launch.py
  as2_aerial_platforms/as2_platform_multirotor_simulator/package.xml
  as2_aerial_platforms/as2_platform_multirotor_simulator/src/as2_platform_multirotor_simulator.cpp
  as2_aerial_platforms/as2_platform_multirotor_simulator/src/as2_platform_multirotor_simulator_node.cpp
  as2_aerial_platforms/as2_platform_multirotor_simulator/tests/CMakeLists.txt
  as2_aerial_platforms/as2_platform_multirotor_simulator/tests/as2_platform_multirotor_simulator_gtest.cpp
Labels: enhancement, platform

#480 [as2_gazebo_assets] Add actuators bridge
  as2_simulation_assets/as2_gazebo_assets/hooks/resource_paths.dsv.in
  as2_simulation_assets/as2_gazebo_assets/hooks/resource_paths.sh
  as2_simulation_assets/as2_gazebo_assets/launch/monitor_sim.py
  as2_simulation_assets/as2_gazebo_assets/models/quadrotor_base/quadrotor_base.sdf.jinja
  as2_simulation_assets/as2_gazebo_assets/scripts/jinja_gen.py
  as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/bridges/bridges.py
  as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/models/drone.py
Labels: enhancement
