Repository aerostack2/aerostack2, pull requests merged in 2025-03, with the labels that each got.

#760 [as2_state_estimator] Fix tf_handler instantiation in plugin base
  as2_state_estimator/include/as2_state_estimator/plugin_base.hpp
Labels: bug

#761 [as2_state_estimator] Add ground truth and odometry fuse node
  as2_state_estimator/include/as2_state_estimator/plugin_base.hpp
  as2_state_estimator/launch/raw_odometry_ground_truth_fuse.launch.py
  as2_state_estimator/plugins/raw_odometry/CMakeLists.txt
  as2_state_estimator/plugins/raw_odometry/config/ground_truth_fuse.yaml
  as2_state_estimator/plugins/raw_odometry/config/plugin_default.yaml
  as2_state_estimator/plugins/raw_odometry/include/ground_truth_fuse.hpp
  as2_state_estimator/plugins/raw_odometry/include/raw_odometry.hpp
  as2_state_estimator/plugins/raw_odometry/src/ground_truth_fuse_node.cpp
Labels: enhancement

#759 [as2_behaviors_trajectory_generation] Generate partial trajectory and new yaw to face the next refernce
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/config/config_default.yaml
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
  as2_msgs/msg/YawMode.msg
  as2_python_api/as2_python_api/modules/trajectory_generation_module.py
Labels: enhancement

#762 [as2_python_api] Mission Interpreter improvements using multiples missions ids
  as2_msgs/msg/MissionUpdate.msg
  as2_python_api/as2_python_api/mission_interpreter/mission.py
  as2_python_api/as2_python_api/mission_interpreter/mission_interpreter.py
  as2_python_api/as2_python_api/mission_interpreter/ros2_adapter.py
  as2_python_api/as2_python_api/test/test_interpreter.py
Labels: enhancement

#764 [as2_platform_multirotor_simulator] Use as2 interface to convert commands and states
  as2_aerial_platforms/as2_platform_multirotor_simulator/CMakeLists.txt
  as2_aerial_platforms/as2_platform_multirotor_simulator/config/world_config.yaml
  as2_aerial_platforms/as2_platform_multirotor_simulator/include/as2_platform_multirotor_simulator/as2_interface.hpp
  as2_aerial_platforms/as2_platform_multirotor_simulator/include/as2_platform_multirotor_simulator/as2_platform_multirotor_simulator.hpp
  as2_aerial_platforms/as2_platform_multirotor_simulator/src/as2_interface.cpp
  as2_aerial_platforms/as2_platform_multirotor_simulator/src/as2_platform_multirotor_simulator.cpp
  as2_aerial_platforms/as2_platform_multirotor_simulator/tests/as2_platform_multirotor_simulator_fly_gtest.cpp
Labels: enhancement

#770 [as2_behaviors_trajectory_generation] Fix setpoints evaluation
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
Labels: bug

#772 [as2_platform_multirotor_simulator] Fix imu read
  as2_aerial_platforms/as2_platform_multirotor_simulator/src/as2_platform_multirotor_simulator.cpp
Labels: bug

#771 [as2_behaviors_perception] Support arducam
  as2_hardware_drivers/as2_usb_camera_interface/config/config_file_default.yaml
  as2_hardware_drivers/as2_usb_camera_interface/include/as2_usb_camera_interface/as2_usb_camera_interface.hpp
  as2_hardware_drivers/as2_usb_camera_interface/src/as2_usb_camera_interface.cpp
Labels: enhancement

#769 [as2_behaviors_trajectory_generator] Modify a set of waypoints due to frame offsets
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/config/config_default.yaml
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
Labels: enhancement

#775 [as2_state_estimator] Replace timer for odometry callback in ground_truth_odometry_fuse
  as2_state_estimator/launch/ground_truth_odometry_fuse_state_estimator.launch.py
  as2_state_estimator/plugins/ground_truth_odometry_fuse/config/plugin_default.yaml
  as2_state_estimator/plugins/ground_truth_odometry_fuse/include/ground_truth_odometry_fuse.hpp
Labels: enhancement, state_estimator

#776 [as2_behaviors_trajectory_generation] Modify a wp
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/config/config_default.yaml
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/include/generate_polynomial_trajectory_behavior/generate_polynomial_trajectory_behavior.hpp
  as2_behaviors/as2_behaviors_trajectory_generation/generate_polynomial_trajectory_behavior/src/generate_polynomial_trajectory_behavior.cpp
Labels: enhancement

#782 [as2_state_estimator] Fix odom topic default parameter in ground_truth_odometry_fuse plugin
  as2_state_estimator/plugins/ground_truth_odometry_fuse/config/plugin_default.yaml
Labels: enhancement
